package xyz.proteanbear.template.excel;

import xyz.proteanbear.template.annotation.PbPOIExcelTitle;

import java.util.Date;

/**
 * 
 * 成都金控数据版权所有
 * @className: ReportInfo
 * @description : 体测结果
 * @author: create by liudongbin
 * @email: 756665368@qq.com
 * @date: 2018年6月26日下午2:29:10
 * @version: 1.0
 * Copyright(C)2018 by
 * Chengdu Financial Holding Data Services
 * All rights reserved.
 *
 */
public class ReportInfo {
    /**
	 * 主键，报告ID
     */
    private String reportid;

    /**
     * 会员号
     */
    @PbPOIExcelTitle("会员号")
    private String mid;

    /**
     * 卡号
     */
    @PbPOIExcelTitle("卡号")
    private String cardno;

    /**
     * 手机号
     */
    private String phone;

    /**
     * 姓名
     */
    @PbPOIExcelTitle("姓名")
    private String name;

    /**
     * 性别
     */
    @PbPOIExcelTitle("性别")
    private String sex;

    /**
     * 年龄
     */
    @PbPOIExcelTitle("年龄")
    private String age;

    /**
     * 出生日期
     */
    @PbPOIExcelTitle(value="出生日期",dateFormat="yyyy-MM-dd")
    private Date birthday;

    /**
     * 身份证
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_info.work_unit
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("工作单位")
    private String workUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_info.dept_info
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("部门信息")
    private String deptInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_info.registration_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle(value="注册日期")
    private String registrationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_info.appointment_time
     * 预约时间
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    private String appointmentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_info.complet_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle(value="测试时间")
    private String completTime;

    /**
     * 身高
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("身高")
    private String height;

    /**
        身高_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("身高_得分")
    private String heightScore;

    /**
     * 身高_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("身高_评价")
    private String heightEvaluation;

    /**
     * 体重
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("体重")
    private String weight;

    /**
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    private String weightScore;

    /**
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    private String weightEvaluation;

    /**
     * 身高标准体重
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("身高标准体重")
    private String normal;

    /**
     * 身高标准体重_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("身高标准体重_得分")
    private String normalScore;

    /**
     * 身高标准体重_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("身高标准体重_评价")
    private String normalEvaluation;

    /**
     * 肺活量
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("肺活量")
    private String vitalCapacity;

    /**
     * 肺活量_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("肺活量_得分")
    private String vitalCapacityScore;

    /**
     * 肺活量_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("肺活量_评价")
    private String vitalCapacityEvaluation;

    /**
     * 台阶指数
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("台阶指数")
    private String step;

    /**
     * 台阶指数_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("台阶指数_得分")
    private String stepScore;

    /**
     * 台阶指数_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("台阶指数_评价")
    private String stepEvaluation;

    /**
     * 运动时间
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("运动时间")
    private String runDuration;

    /**
     * 1分钟后脉搏
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("1分钟后脉搏")
    private String oneMinLaterPulse;

    /**
     * 2分钟后脉搏
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("2分钟后脉搏")
    private String twoMinLaterPulse;

    /**
     * 3分钟后脉搏
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("3分钟后脉搏")
    private String threeMinLaterPulse;

    /**
     * 握力
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("握力")
    private String grippower;

    /**
     * 握力_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("握力_得分")
    private String grippowerScore;

    /**
     * 握力_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("握力_评价")
    private String grippowerEvaluation;

    /**
     * 纵跳
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("纵跳")
    private String verticalJump;

    /**
     * 纵跳_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("纵跳_得分")
    private String verticalJumpScore;

    /**
     * 纵跳_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("纵跳_评价")
    private String verticalJumpEvaluation;

    /**
     * 俯卧撑
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("俯卧撑")
    private String pushUp;

    /**
     * 俯卧撑_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("俯卧撑_得分")
    private String pushUpScore;

    /**
     * 俯卧撑_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("俯卧撑_评价")
    private String pushUpEvaluation;

    /**
     * 仰卧起坐
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("仰卧起坐")
    private String sitUp;

    /**
     * 仰卧起坐_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("仰卧起坐_得分")
    private String sitUpScore;

    /**
     * 仰卧起坐_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("仰卧起坐_评价")
    private String sitUpEvaluation;

    /**
     * 坐位体前屈
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("坐位体前屈")
    private String sitandreach;

    /**
     * 坐位体前屈_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("坐位体前屈_得分")
    private String sitandreachScrore;

    /**
     * 坐位体前屈_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("坐位体前屈_评价")
    private String sitandreachEvaluation;

    /**
     * 闭眼单脚站立
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("闭眼单脚站立")
    private String olstanding;

    /**
     * 闭眼单脚站立_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("闭眼单脚站立_得分")
    private String olstandingScore;

    /**
     * 闭眼单脚站立_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("闭眼单脚站立_评价")
    private String olstandingEvaluation;

    /**
     * 网球掷远
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("网球掷远")
    private String tennisThrow;

    /**
     * 网球掷远_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("网球掷远_得分")
    private String tennisThrowScore;

    /**
     * 网球掷远_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("网球掷远_评价")
    private String tennisThrowsEvaluation;

    /**
     * 双脚连续跳
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("双脚连续跳")
    private String doubleJump;

    /**
     * 双脚连续跳_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("双脚连续跳_得分")
    private String doubleJumpScore;

    /**
     * 双脚连续跳_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("双脚连续跳_评价")
    private String doubleJumpEvaluation;

    /**
     * 立定跳远
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("立定跳远")
    private String standingLeap;

    /**
     * 立定跳远_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("立定跳远_得分")
    private String standingLeapScore;

    /**
     * 立定跳远_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("立定跳远_评价")
    private String standingLeapEvaluation;

    /**
     * 走平衡木
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("走平衡木")
    private String balanceBeam;

    /**
     * 走平衡木_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("走平衡木_得分")
    private String balanceBeamScore;

    /**
     * 走平衡木_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("走平衡木_评价")
    private String balanceBeamEvaluation;

    /**
     * 10米折返跑
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("10米折返跑")
    private String tenmeterRetrace;

    /**
     * 10米折返跑_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("10米折返跑_得分")
    private String tenmeterRetraceScore;

    /**
     * 10米折返跑_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("10米折返跑_评价")
    private String tenmeterRetraceEvaluation;

    /**
     * 选择反应时
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("选择反应时")
    private String choicetime;

    /**
     * 选择反应时_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("选择反应时_得分")
    private String choicetimeScore;

    /**
     * 选择反应时_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("选择反应时_评价")
    private String choicetimeEvaluation;

    /**
     * 综合评分_得分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("综合评分_得分")
    private String comprehensiveScore;

    /**
     * 综合评分_评价
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("综合评分_评价")
    private String comprehensiveEvaluation;

    /**
     * （国民体质）综合评分
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    @PbPOIExcelTitle("（国民体质）综合评分")
    private String physicalScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.reportId
     *
     * @return the value of t_report_info.reportId
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getReportid() {
        return reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.reportId
     *
     * @param reportid the value for t_report_info.reportId
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setReportid(String reportid) {
        this.reportid = reportid == null ? null : reportid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.mid
     *
     * @return the value of t_report_info.mid
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.mid
     *
     * @param mid the value for t_report_info.mid
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.cardno
     *
     * @return the value of t_report_info.cardno
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.cardno
     *
     * @param cardno the value for t_report_info.cardno
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.phone
     *
     * @return the value of t_report_info.phone
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.phone
     *
     * @param phone the value for t_report_info.phone
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.name
     *
     * @return the value of t_report_info.name
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.name
     *
     * @param name the value for t_report_info.name
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sex
     *
     * @return the value of t_report_info.sex
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sex
     *
     * @param sex the value for t_report_info.sex
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.age
     *
     * @return the value of t_report_info.age
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.age
     *
     * @param age the value for t_report_info.age
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.birthday
     *
     * @return the value of t_report_info.birthday
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.birthday
     *
     * @param birthday the value for t_report_info.birthday
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday == null ? null : birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.idcard
     *
     * @return the value of t_report_info.idcard
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.idcard
     *
     * @param idcard the value for t_report_info.idcard
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.work_unit
     *
     * @return the value of t_report_info.work_unit
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getWorkUnit() {
        return workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.work_unit
     *
     * @param workUnit the value for t_report_info.work_unit
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit == null ? null : workUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.dept_info
     *
     * @return the value of t_report_info.dept_info
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getDeptInfo() {
        return deptInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.dept_info
     *
     * @param deptInfo the value for t_report_info.dept_info
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setDeptInfo(String deptInfo) {
        this.deptInfo = deptInfo == null ? null : deptInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.registration_time
     *
     * @return the value of t_report_info.registration_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getRegistrationTime() {
        return registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.registration_time
     *
     * @param registrationTime the value for t_report_info.registration_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setRegistrationTime(String registrationTime) {
        this.registrationTime = registrationTime == null ? null : registrationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.appointment_time
     *
     * @return the value of t_report_info.appointment_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.appointment_time
     *
     * @param appointmentTime the value for t_report_info.appointment_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setAppointmentTime(String appointmentTime) {
        this.appointmentTime = appointmentTime == null ? null : appointmentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.complet_time
     *
     * @return the value of t_report_info.complet_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getCompletTime() {
        return completTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.complet_time
     *
     * @param completTime the value for t_report_info.complet_time
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setCompletTime(String completTime) {
        this.completTime = completTime == null ? null : completTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.height
     *
     * @return the value of t_report_info.height
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.height
     *
     * @param height the value for t_report_info.height
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.height_score
     *
     * @return the value of t_report_info.height_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getHeightScore() {
        return heightScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.height_score
     *
     * @param heightScore the value for t_report_info.height_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setHeightScore(String heightScore) {
        this.heightScore = heightScore == null ? null : heightScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.height_evaluation
     *
     * @return the value of t_report_info.height_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getHeightEvaluation() {
        return heightEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.height_evaluation
     *
     * @param heightEvaluation the value for t_report_info.height_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setHeightEvaluation(String heightEvaluation) {
        this.heightEvaluation = heightEvaluation == null ? null : heightEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.weight
     *
     * @return the value of t_report_info.weight
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.weight
     *
     * @param weight the value for t_report_info.weight
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.weight_score
     *
     * @return the value of t_report_info.weight_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getWeightScore() {
        return weightScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.weight_score
     *
     * @param weightScore the value for t_report_info.weight_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setWeightScore(String weightScore) {
        this.weightScore = weightScore == null ? null : weightScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.weight_evaluation
     *
     * @return the value of t_report_info.weight_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getWeightEvaluation() {
        return weightEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.weight_evaluation
     *
     * @param weightEvaluation the value for t_report_info.weight_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setWeightEvaluation(String weightEvaluation) {
        this.weightEvaluation = weightEvaluation == null ? null : weightEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.normal
     *
     * @return the value of t_report_info.normal
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getNormal() {
        return normal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.normal
     *
     * @param normal the value for t_report_info.normal
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setNormal(String normal) {
        this.normal = normal == null ? null : normal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.normal_score
     *
     * @return the value of t_report_info.normal_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getNormalScore() {
        return normalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.normal_score
     *
     * @param normalScore the value for t_report_info.normal_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setNormalScore(String normalScore) {
        this.normalScore = normalScore == null ? null : normalScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.normal_evaluation
     *
     * @return the value of t_report_info.normal_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getNormalEvaluation() {
        return normalEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.normal_evaluation
     *
     * @param normalEvaluation the value for t_report_info.normal_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setNormalEvaluation(String normalEvaluation) {
        this.normalEvaluation = normalEvaluation == null ? null : normalEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.vital_capacity
     *
     * @return the value of t_report_info.vital_capacity
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getVitalCapacity() {
        return vitalCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.vital_capacity
     *
     * @param vitalCapacity the value for t_report_info.vital_capacity
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setVitalCapacity(String vitalCapacity) {
        this.vitalCapacity = vitalCapacity == null ? null : vitalCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.vital_capacity_score
     *
     * @return the value of t_report_info.vital_capacity_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getVitalCapacityScore() {
        return vitalCapacityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.vital_capacity_score
     *
     * @param vitalCapacityScore the value for t_report_info.vital_capacity_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setVitalCapacityScore(String vitalCapacityScore) {
        this.vitalCapacityScore = vitalCapacityScore == null ? null : vitalCapacityScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.vital_capacity_evaluation
     *
     * @return the value of t_report_info.vital_capacity_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getVitalCapacityEvaluation() {
        return vitalCapacityEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.vital_capacity_evaluation
     *
     * @param vitalCapacityEvaluation the value for t_report_info.vital_capacity_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setVitalCapacityEvaluation(String vitalCapacityEvaluation) {
        this.vitalCapacityEvaluation = vitalCapacityEvaluation == null ? null : vitalCapacityEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.step
     *
     * @return the value of t_report_info.step
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.step
     *
     * @param step the value for t_report_info.step
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.step_score
     *
     * @return the value of t_report_info.step_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getStepScore() {
        return stepScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.step_score
     *
     * @param stepScore the value for t_report_info.step_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setStepScore(String stepScore) {
        this.stepScore = stepScore == null ? null : stepScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.step_evaluation
     *
     * @return the value of t_report_info.step_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getStepEvaluation() {
        return stepEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.step_evaluation
     *
     * @param stepEvaluation the value for t_report_info.step_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setStepEvaluation(String stepEvaluation) {
        this.stepEvaluation = stepEvaluation == null ? null : stepEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.run_duration
     *
     * @return the value of t_report_info.run_duration
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getRunDuration() {
        return runDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.run_duration
     *
     * @param runDuration the value for t_report_info.run_duration
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setRunDuration(String runDuration) {
        this.runDuration = runDuration == null ? null : runDuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.one_min_later_pulse
     *
     * @return the value of t_report_info.one_min_later_pulse
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getOneMinLaterPulse() {
        return oneMinLaterPulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.one_min_later_pulse
     *
     * @param oneMinLaterPulse the value for t_report_info.one_min_later_pulse
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setOneMinLaterPulse(String oneMinLaterPulse) {
        this.oneMinLaterPulse = oneMinLaterPulse == null ? null : oneMinLaterPulse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.two_min_later_pulse
     *
     * @return the value of t_report_info.two_min_later_pulse
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTwoMinLaterPulse() {
        return twoMinLaterPulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.two_min_later_pulse
     *
     * @param twoMinLaterPulse the value for t_report_info.two_min_later_pulse
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTwoMinLaterPulse(String twoMinLaterPulse) {
        this.twoMinLaterPulse = twoMinLaterPulse == null ? null : twoMinLaterPulse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.three_min_later_pulse
     *
     * @return the value of t_report_info.three_min_later_pulse
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getThreeMinLaterPulse() {
        return threeMinLaterPulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.three_min_later_pulse
     *
     * @param threeMinLaterPulse the value for t_report_info.three_min_later_pulse
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setThreeMinLaterPulse(String threeMinLaterPulse) {
        this.threeMinLaterPulse = threeMinLaterPulse == null ? null : threeMinLaterPulse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.grippower
     *
     * @return the value of t_report_info.grippower
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getGrippower() {
        return grippower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.grippower
     *
     * @param grippower the value for t_report_info.grippower
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setGrippower(String grippower) {
        this.grippower = grippower == null ? null : grippower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.grippower_score
     *
     * @return the value of t_report_info.grippower_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getGrippowerScore() {
        return grippowerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.grippower_score
     *
     * @param grippowerScore the value for t_report_info.grippower_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setGrippowerScore(String grippowerScore) {
        this.grippowerScore = grippowerScore == null ? null : grippowerScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.grippower_evaluation
     *
     * @return the value of t_report_info.grippower_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getGrippowerEvaluation() {
        return grippowerEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.grippower_evaluation
     *
     * @param grippowerEvaluation the value for t_report_info.grippower_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setGrippowerEvaluation(String grippowerEvaluation) {
        this.grippowerEvaluation = grippowerEvaluation == null ? null : grippowerEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.vertical_jump
     *
     * @return the value of t_report_info.vertical_jump
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getVerticalJump() {
        return verticalJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.vertical_jump
     *
     * @param verticalJump the value for t_report_info.vertical_jump
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setVerticalJump(String verticalJump) {
        this.verticalJump = verticalJump == null ? null : verticalJump.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.vertical_jump_score
     *
     * @return the value of t_report_info.vertical_jump_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getVerticalJumpScore() {
        return verticalJumpScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.vertical_jump_score
     *
     * @param verticalJumpScore the value for t_report_info.vertical_jump_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setVerticalJumpScore(String verticalJumpScore) {
        this.verticalJumpScore = verticalJumpScore == null ? null : verticalJumpScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.vertical_jump_evaluation
     *
     * @return the value of t_report_info.vertical_jump_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getVerticalJumpEvaluation() {
        return verticalJumpEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.vertical_jump_evaluation
     *
     * @param verticalJumpEvaluation the value for t_report_info.vertical_jump_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setVerticalJumpEvaluation(String verticalJumpEvaluation) {
        this.verticalJumpEvaluation = verticalJumpEvaluation == null ? null : verticalJumpEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.push_up
     *
     * @return the value of t_report_info.push_up
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getPushUp() {
        return pushUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.push_up
     *
     * @param pushUp the value for t_report_info.push_up
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setPushUp(String pushUp) {
        this.pushUp = pushUp == null ? null : pushUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.push_up_score
     *
     * @return the value of t_report_info.push_up_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getPushUpScore() {
        return pushUpScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.push_up_score
     *
     * @param pushUpScore the value for t_report_info.push_up_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setPushUpScore(String pushUpScore) {
        this.pushUpScore = pushUpScore == null ? null : pushUpScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.push_up_evaluation
     *
     * @return the value of t_report_info.push_up_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getPushUpEvaluation() {
        return pushUpEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.push_up_evaluation
     *
     * @param pushUpEvaluation the value for t_report_info.push_up_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setPushUpEvaluation(String pushUpEvaluation) {
        this.pushUpEvaluation = pushUpEvaluation == null ? null : pushUpEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sit_up
     *
     * @return the value of t_report_info.sit_up
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSitUp() {
        return sitUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sit_up
     *
     * @param sitUp the value for t_report_info.sit_up
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSitUp(String sitUp) {
        this.sitUp = sitUp == null ? null : sitUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sit_up_score
     *
     * @return the value of t_report_info.sit_up_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSitUpScore() {
        return sitUpScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sit_up_score
     *
     * @param sitUpScore the value for t_report_info.sit_up_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSitUpScore(String sitUpScore) {
        this.sitUpScore = sitUpScore == null ? null : sitUpScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sit_up_evaluation
     *
     * @return the value of t_report_info.sit_up_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSitUpEvaluation() {
        return sitUpEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sit_up_evaluation
     *
     * @param sitUpEvaluation the value for t_report_info.sit_up_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSitUpEvaluation(String sitUpEvaluation) {
        this.sitUpEvaluation = sitUpEvaluation == null ? null : sitUpEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sitandreach
     *
     * @return the value of t_report_info.sitandreach
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSitandreach() {
        return sitandreach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sitandreach
     *
     * @param sitandreach the value for t_report_info.sitandreach
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSitandreach(String sitandreach) {
        this.sitandreach = sitandreach == null ? null : sitandreach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sitandreach_scrore
     *
     * @return the value of t_report_info.sitandreach_scrore
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSitandreachScrore() {
        return sitandreachScrore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sitandreach_scrore
     *
     * @param sitandreachScrore the value for t_report_info.sitandreach_scrore
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSitandreachScrore(String sitandreachScrore) {
        this.sitandreachScrore = sitandreachScrore == null ? null : sitandreachScrore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.sitandreach_evaluation
     *
     * @return the value of t_report_info.sitandreach_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getSitandreachEvaluation() {
        return sitandreachEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.sitandreach_evaluation
     *
     * @param sitandreachEvaluation the value for t_report_info.sitandreach_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setSitandreachEvaluation(String sitandreachEvaluation) {
        this.sitandreachEvaluation = sitandreachEvaluation == null ? null : sitandreachEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.olstanding
     *
     * @return the value of t_report_info.olstanding
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getOlstanding() {
        return olstanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.olstanding
     *
     * @param olstanding the value for t_report_info.olstanding
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setOlstanding(String olstanding) {
        this.olstanding = olstanding == null ? null : olstanding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.olstanding_score
     *
     * @return the value of t_report_info.olstanding_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getOlstandingScore() {
        return olstandingScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.olstanding_score
     *
     * @param olstandingScore the value for t_report_info.olstanding_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setOlstandingScore(String olstandingScore) {
        this.olstandingScore = olstandingScore == null ? null : olstandingScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.olstanding_evaluation
     *
     * @return the value of t_report_info.olstanding_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getOlstandingEvaluation() {
        return olstandingEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.olstanding_evaluation
     *
     * @param olstandingEvaluation the value for t_report_info.olstanding_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setOlstandingEvaluation(String olstandingEvaluation) {
        this.olstandingEvaluation = olstandingEvaluation == null ? null : olstandingEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.tennis_throw
     *
     * @return the value of t_report_info.tennis_throw
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTennisThrow() {
        return tennisThrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.tennis_throw
     *
     * @param tennisThrow the value for t_report_info.tennis_throw
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTennisThrow(String tennisThrow) {
        this.tennisThrow = tennisThrow == null ? null : tennisThrow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.tennis_throw_score
     *
     * @return the value of t_report_info.tennis_throw_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTennisThrowScore() {
        return tennisThrowScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.tennis_throw_score
     *
     * @param tennisThrowScore the value for t_report_info.tennis_throw_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTennisThrowScore(String tennisThrowScore) {
        this.tennisThrowScore = tennisThrowScore == null ? null : tennisThrowScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.tennis_throws_evaluation
     *
     * @return the value of t_report_info.tennis_throws_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTennisThrowsEvaluation() {
        return tennisThrowsEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.tennis_throws_evaluation
     *
     * @param tennisThrowsEvaluation the value for t_report_info.tennis_throws_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTennisThrowsEvaluation(String tennisThrowsEvaluation) {
        this.tennisThrowsEvaluation = tennisThrowsEvaluation == null ? null : tennisThrowsEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.double_jump
     *
     * @return the value of t_report_info.double_jump
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getDoubleJump() {
        return doubleJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.double_jump
     *
     * @param doubleJump the value for t_report_info.double_jump
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setDoubleJump(String doubleJump) {
        this.doubleJump = doubleJump == null ? null : doubleJump.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.double_jump_score
     *
     * @return the value of t_report_info.double_jump_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getDoubleJumpScore() {
        return doubleJumpScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.double_jump_score
     *
     * @param doubleJumpScore the value for t_report_info.double_jump_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setDoubleJumpScore(String doubleJumpScore) {
        this.doubleJumpScore = doubleJumpScore == null ? null : doubleJumpScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.double_jump_evaluation
     *
     * @return the value of t_report_info.double_jump_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getDoubleJumpEvaluation() {
        return doubleJumpEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.double_jump_evaluation
     *
     * @param doubleJumpEvaluation the value for t_report_info.double_jump_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setDoubleJumpEvaluation(String doubleJumpEvaluation) {
        this.doubleJumpEvaluation = doubleJumpEvaluation == null ? null : doubleJumpEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.standing_leap
     *
     * @return the value of t_report_info.standing_leap
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getStandingLeap() {
        return standingLeap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.standing_leap
     *
     * @param standingLeap the value for t_report_info.standing_leap
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setStandingLeap(String standingLeap) {
        this.standingLeap = standingLeap == null ? null : standingLeap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.standing_leap_score
     *
     * @return the value of t_report_info.standing_leap_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getStandingLeapScore() {
        return standingLeapScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.standing_leap_score
     *
     * @param standingLeapScore the value for t_report_info.standing_leap_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setStandingLeapScore(String standingLeapScore) {
        this.standingLeapScore = standingLeapScore == null ? null : standingLeapScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.standing_leap_evaluation
     *
     * @return the value of t_report_info.standing_leap_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getStandingLeapEvaluation() {
        return standingLeapEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.standing_leap_evaluation
     *
     * @param standingLeapEvaluation the value for t_report_info.standing_leap_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setStandingLeapEvaluation(String standingLeapEvaluation) {
        this.standingLeapEvaluation = standingLeapEvaluation == null ? null : standingLeapEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.balance_beam
     *
     * @return the value of t_report_info.balance_beam
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getBalanceBeam() {
        return balanceBeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.balance_beam
     *
     * @param balanceBeam the value for t_report_info.balance_beam
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setBalanceBeam(String balanceBeam) {
        this.balanceBeam = balanceBeam == null ? null : balanceBeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.balance_beam_score
     *
     * @return the value of t_report_info.balance_beam_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getBalanceBeamScore() {
        return balanceBeamScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.balance_beam_score
     *
     * @param balanceBeamScore the value for t_report_info.balance_beam_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setBalanceBeamScore(String balanceBeamScore) {
        this.balanceBeamScore = balanceBeamScore == null ? null : balanceBeamScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.balance_beam_evaluation
     *
     * @return the value of t_report_info.balance_beam_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getBalanceBeamEvaluation() {
        return balanceBeamEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.balance_beam_evaluation
     *
     * @param balanceBeamEvaluation the value for t_report_info.balance_beam_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setBalanceBeamEvaluation(String balanceBeamEvaluation) {
        this.balanceBeamEvaluation = balanceBeamEvaluation == null ? null : balanceBeamEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.tenmeter_retrace
     *
     * @return the value of t_report_info.tenmeter_retrace
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTenmeterRetrace() {
        return tenmeterRetrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.tenmeter_retrace
     *
     * @param tenmeterRetrace the value for t_report_info.tenmeter_retrace
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTenmeterRetrace(String tenmeterRetrace) {
        this.tenmeterRetrace = tenmeterRetrace == null ? null : tenmeterRetrace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.tenmeter_retrace_score
     *
     * @return the value of t_report_info.tenmeter_retrace_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTenmeterRetraceScore() {
        return tenmeterRetraceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.tenmeter_retrace_score
     *
     * @param tenmeterRetraceScore the value for t_report_info.tenmeter_retrace_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTenmeterRetraceScore(String tenmeterRetraceScore) {
        this.tenmeterRetraceScore = tenmeterRetraceScore == null ? null : tenmeterRetraceScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.tenmeter_retrace_evaluation
     *
     * @return the value of t_report_info.tenmeter_retrace_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getTenmeterRetraceEvaluation() {
        return tenmeterRetraceEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.tenmeter_retrace_evaluation
     *
     * @param tenmeterRetraceEvaluation the value for t_report_info.tenmeter_retrace_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setTenmeterRetraceEvaluation(String tenmeterRetraceEvaluation) {
        this.tenmeterRetraceEvaluation = tenmeterRetraceEvaluation == null ? null : tenmeterRetraceEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.choicetime
     *
     * @return the value of t_report_info.choicetime
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getChoicetime() {
        return choicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.choicetime
     *
     * @param choicetime the value for t_report_info.choicetime
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setChoicetime(String choicetime) {
        this.choicetime = choicetime == null ? null : choicetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.choicetime_score
     *
     * @return the value of t_report_info.choicetime_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getChoicetimeScore() {
        return choicetimeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.choicetime_score
     *
     * @param choicetimeScore the value for t_report_info.choicetime_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setChoicetimeScore(String choicetimeScore) {
        this.choicetimeScore = choicetimeScore == null ? null : choicetimeScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.choicetime_evaluation
     *
     * @return the value of t_report_info.choicetime_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getChoicetimeEvaluation() {
        return choicetimeEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.choicetime_evaluation
     *
     * @param choicetimeEvaluation the value for t_report_info.choicetime_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setChoicetimeEvaluation(String choicetimeEvaluation) {
        this.choicetimeEvaluation = choicetimeEvaluation == null ? null : choicetimeEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.comprehensive_score
     *
     * @return the value of t_report_info.comprehensive_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getComprehensiveScore() {
        return comprehensiveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.comprehensive_score
     *
     * @param comprehensiveScore the value for t_report_info.comprehensive_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setComprehensiveScore(String comprehensiveScore) {
        this.comprehensiveScore = comprehensiveScore == null ? null : comprehensiveScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.comprehensive_evaluation
     *
     * @return the value of t_report_info.comprehensive_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getComprehensiveEvaluation() {
        return comprehensiveEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.comprehensive_evaluation
     *
     * @param comprehensiveEvaluation the value for t_report_info.comprehensive_evaluation
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setComprehensiveEvaluation(String comprehensiveEvaluation) {
        this.comprehensiveEvaluation = comprehensiveEvaluation == null ? null : comprehensiveEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_info.physical_score
     *
     * @return the value of t_report_info.physical_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public String getPhysicalScore() {
        return physicalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_info.physical_score
     *
     * @param physicalScore the value for t_report_info.physical_score
     *
     * @mbggenerated Tue Jun 26 14:28:53 CST 2018
     */
    public void setPhysicalScore(String physicalScore) {
        this.physicalScore = physicalScore == null ? null : physicalScore.trim();
    }
}